chore: update

diff --git a/.github/workflows/provisioning.yml b/.github/workflows/provisioning.yml
--- a/.github/workflows/provisioning.yml
+++ b/.github/workflows/provisioning.yml
@@ -51,32 +51,8 @@ jobs:
           mkdir -p ~/.ssh
           echo "${{ secrets.VPS_OPS_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
 
-      - name: ⚡ Run Bootstrap Playbook
-        env:
-          123: ${{ vars.BOOTSTRAP_HOSTS }}
-          ANSIBLE_USER: ${{ github.event.inputs.SSH_USER }}
-          PUB_KEY_PATH: ~/.ssh/id_rsa.pub
-          ANSIBLE_STDOUT_CALLBACK: yaml
-          ANSIBLE_VERBOSITY: 2
+      - name: ⚡ Throw error
         run: |
-          echo "::group::🚀 Start proces"
-    
-          # Symulacja błędu (zamień 'false' na cokolwiek co rzuca błąd)
-          {
-            echo "Wykonuję ryzykowną operację..."
-            false # To jest nasz "throw" (exit code 1)
-            
-            echo "::endgroup::" # To się nigdy nie wykona
-          } || {
-          # CATCH BLOCK
-          EXIT_CODE=$?
-          echo "::endgroup::"
-          
-          # Logujemy błąd do sekcji Annotations
-          echo "::error title=Critical Failure::Złapano błąd (Exit Code: $EXIT_CODE). Przerywam pipeline!"
-          
-          # KLUCZOWE: Bez tego linia poniżej sprawi, że krok będzie ZIELONY
-          exit $EXIT_CODE
-          }
-      
+          echo "::error::bla"
+          exit 1
             
